/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RkFavoriteToggleDetail, RkFilterChangeDetail, RkFilterOption, RkIngredient, RkMealSlotDetail } from "./interfaces";
export { RkFavoriteToggleDetail, RkFilterChangeDetail, RkFilterOption, RkIngredient, RkMealSlotDetail } from "./interfaces";
export namespace Components {
    /**
     * Small pill used for recipe categories, cuisines and tags.
     */
    interface RkBadge {
        /**
          * Text to render when no slotted content is provided.
          * @default ''
         */
        "label": string;
        /**
          * Visual treatment of the pill.
          * @default 'neutral'
         */
        "variant": 'neutral' | 'primary' | 'danger';
    }
    /**
     * Placeholder shown when a list has nothing to display.
     */
    interface RkEmptyState {
        /**
          * Bold headline, e.g. `"No recipes found"`.
          * @default 'Nothing here yet'
         */
        "heading": string;
        /**
          * Emoji or short glyph shown above the heading.
          * @default '🍳'
         */
        "icon": string;
        /**
          * Supporting sentence explaining what to do next.
          * @default ''
         */
        "message": string;
    }
    /**
     * Labelled dropdown used to narrow a recipe list.
     * `options` is an object array, so hosts must set it as a **property** rather
     * than an attribute. A JSON string is also accepted as a convenience for
     * server-rendered markup.
     */
    interface RkFilterSelect {
        /**
          * Disables the control, e.g. while its choices are still loading.
          * @default false
         */
        "disabled": boolean;
        /**
          * Visible label above the control.
          * @default ''
         */
        "label": string;
        /**
          * Echoed back in `rkFilterChange` so one handler can serve several filters.
         */
        "name": string;
        /**
          * Choices to render. Accepts an array or a JSON-encoded array.
          * @default []
         */
        "options": RkFilterOption[] | string;
        /**
          * Label for the "no filter" entry.
          * @default 'All'
         */
        "placeholder": string;
        /**
          * Currently selected option value. Empty string selects the reset entry.
          * @default ''
         */
        "value": string;
    }
    /**
     * Checklist of ingredients for the recipe details page.
     * `items` is an object array, so hosts set it as a **property**. A JSON string
     * is accepted as well. Ticking a row is local UI state - a shopping aid - so it
     * deliberately emits nothing.
     */
    interface RkIngredientList {
        /**
          * Renders checkboxes so the list doubles as a shopping list.
          * @default true
         */
        "checkable": boolean;
        /**
          * Section heading.
          * @default 'Ingredients'
         */
        "heading": string;
        /**
          * Ingredients to render. Accepts an array or a JSON-encoded array.
          * @default []
         */
        "items": RkIngredient[] | string;
    }
    /**
     * One cell of the weekly planner grid: either an assigned recipe or an empty
     * "add" target.
     */
    interface RkMealSlot {
        /**
          * Day key echoed back in every event, e.g. `"monday"`.
         */
        "day": string;
        /**
          * Meal key echoed back in every event, e.g. `"dinner"`.
         */
        "meal": string;
        /**
          * Label for the meal, defaults to a title-cased `meal`.
          * @default ''
         */
        "mealLabel": string;
        /**
          * Id of the assigned recipe. Empty renders the add-target state.
          * @default ''
         */
        "recipeId": string;
        /**
          * Title of the assigned recipe.
          * @default ''
         */
        "recipeName": string;
        /**
          * Thumbnail of the assigned recipe.
          * @default ''
         */
        "recipeThumbnail": string;
    }
    /**
     * Accessible dialog used for the "assign a recipe" and delete-confirmation flows.
     * Visibility is fully controlled by the host through `open`; the component only
     * asks to be closed by emitting `rkClose`.
     */
    interface RkModal {
        /**
          * Dialog heading, also used as its accessible name.
          * @default ''
         */
        "heading": string;
        /**
          * Hides the × button when the host wants to force a footer choice.
          * @default false
         */
        "hideCloseButton": boolean;
        /**
          * Whether the dialog is visible.
          * @default false
         */
        "open": boolean;
    }
    /**
     * Presentational card for a single recipe.
     * The card owns no state: the host decides whether it is favourited and reacts
     * to `rkFavoriteToggle` / `rkOpen`.
     */
    interface RkRecipeCard {
        /**
          * Text of the primary call-to-action.
          * @default 'View recipe'
         */
        "actionLabel": string;
        /**
          * Whether the recipe is currently favourited (drives the heart icon).
          * @default false
         */
        "favorite": boolean;
        /**
          * Hides the favourite button entirely, for read-only contexts.
          * @default false
         */
        "hideFavorite": boolean;
        /**
          * Recipe title shown as the card heading.
          * @default ''
         */
        "name": string;
        /**
          * Identifier passed back in every emitted event.
         */
        "recipeId": string;
        /**
          * Thumbnail URL. A placeholder is drawn when omitted.
          * @default ''
         */
        "thumbnail": string;
    }
    /**
     * A debounced search input.
     * Emits `rkSearch` while the user types (debounced) and `rkSearchSubmit` when
     * they press Enter or the search button, so hosts can choose between
     * search-as-you-type and explicit submission.
     */
    interface RkSearchBar {
        /**
          * Milliseconds to wait after the last keystroke before emitting `rkSearch`.
          * @default 350
         */
        "debounce": number;
        /**
          * Accessible label for the input.
          * @default 'Search recipes'
         */
        "label": string;
        /**
          * Renders a spinner in place of the search icon.
          * @default false
         */
        "loading": boolean;
        /**
          * Placeholder text for the input.
          * @default 'Search recipes…'
         */
        "placeholder": string;
        /**
          * Current query. Kept in sync when the host changes it (e.g. clearing a search).
          * @default ''
         */
        "value": string;
    }
}
export interface RkFilterSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRkFilterSelectElement;
}
export interface RkMealSlotCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRkMealSlotElement;
}
export interface RkModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRkModalElement;
}
export interface RkRecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRkRecipeCardElement;
}
export interface RkSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRkSearchBarElement;
}
declare global {
    /**
     * Small pill used for recipe categories, cuisines and tags.
     */
    interface HTMLRkBadgeElement extends Components.RkBadge, HTMLStencilElement {
    }
    var HTMLRkBadgeElement: {
        prototype: HTMLRkBadgeElement;
        new (): HTMLRkBadgeElement;
    };
    /**
     * Placeholder shown when a list has nothing to display.
     */
    interface HTMLRkEmptyStateElement extends Components.RkEmptyState, HTMLStencilElement {
    }
    var HTMLRkEmptyStateElement: {
        prototype: HTMLRkEmptyStateElement;
        new (): HTMLRkEmptyStateElement;
    };
    interface HTMLRkFilterSelectElementEventMap {
        "rkFilterChange": RkFilterChangeDetail;
    }
    /**
     * Labelled dropdown used to narrow a recipe list.
     * `options` is an object array, so hosts must set it as a **property** rather
     * than an attribute. A JSON string is also accepted as a convenience for
     * server-rendered markup.
     */
    interface HTMLRkFilterSelectElement extends Components.RkFilterSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRkFilterSelectElementEventMap>(type: K, listener: (this: HTMLRkFilterSelectElement, ev: RkFilterSelectCustomEvent<HTMLRkFilterSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRkFilterSelectElementEventMap>(type: K, listener: (this: HTMLRkFilterSelectElement, ev: RkFilterSelectCustomEvent<HTMLRkFilterSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRkFilterSelectElement: {
        prototype: HTMLRkFilterSelectElement;
        new (): HTMLRkFilterSelectElement;
    };
    /**
     * Checklist of ingredients for the recipe details page.
     * `items` is an object array, so hosts set it as a **property**. A JSON string
     * is accepted as well. Ticking a row is local UI state - a shopping aid - so it
     * deliberately emits nothing.
     */
    interface HTMLRkIngredientListElement extends Components.RkIngredientList, HTMLStencilElement {
    }
    var HTMLRkIngredientListElement: {
        prototype: HTMLRkIngredientListElement;
        new (): HTMLRkIngredientListElement;
    };
    interface HTMLRkMealSlotElementEventMap {
        "rkAssign": RkMealSlotDetail;
        "rkRemove": RkMealSlotDetail;
        "rkOpen": RkMealSlotDetail;
    }
    /**
     * One cell of the weekly planner grid: either an assigned recipe or an empty
     * "add" target.
     */
    interface HTMLRkMealSlotElement extends Components.RkMealSlot, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRkMealSlotElementEventMap>(type: K, listener: (this: HTMLRkMealSlotElement, ev: RkMealSlotCustomEvent<HTMLRkMealSlotElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRkMealSlotElementEventMap>(type: K, listener: (this: HTMLRkMealSlotElement, ev: RkMealSlotCustomEvent<HTMLRkMealSlotElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRkMealSlotElement: {
        prototype: HTMLRkMealSlotElement;
        new (): HTMLRkMealSlotElement;
    };
    interface HTMLRkModalElementEventMap {
        "rkClose": void;
    }
    /**
     * Accessible dialog used for the "assign a recipe" and delete-confirmation flows.
     * Visibility is fully controlled by the host through `open`; the component only
     * asks to be closed by emitting `rkClose`.
     */
    interface HTMLRkModalElement extends Components.RkModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRkModalElementEventMap>(type: K, listener: (this: HTMLRkModalElement, ev: RkModalCustomEvent<HTMLRkModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRkModalElementEventMap>(type: K, listener: (this: HTMLRkModalElement, ev: RkModalCustomEvent<HTMLRkModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRkModalElement: {
        prototype: HTMLRkModalElement;
        new (): HTMLRkModalElement;
    };
    interface HTMLRkRecipeCardElementEventMap {
        "rkFavoriteToggle": RkFavoriteToggleDetail;
        "rkOpen": string;
    }
    /**
     * Presentational card for a single recipe.
     * The card owns no state: the host decides whether it is favourited and reacts
     * to `rkFavoriteToggle` / `rkOpen`.
     */
    interface HTMLRkRecipeCardElement extends Components.RkRecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRkRecipeCardElementEventMap>(type: K, listener: (this: HTMLRkRecipeCardElement, ev: RkRecipeCardCustomEvent<HTMLRkRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRkRecipeCardElementEventMap>(type: K, listener: (this: HTMLRkRecipeCardElement, ev: RkRecipeCardCustomEvent<HTMLRkRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRkRecipeCardElement: {
        prototype: HTMLRkRecipeCardElement;
        new (): HTMLRkRecipeCardElement;
    };
    interface HTMLRkSearchBarElementEventMap {
        "rkSearch": string;
        "rkSearchSubmit": string;
    }
    /**
     * A debounced search input.
     * Emits `rkSearch` while the user types (debounced) and `rkSearchSubmit` when
     * they press Enter or the search button, so hosts can choose between
     * search-as-you-type and explicit submission.
     */
    interface HTMLRkSearchBarElement extends Components.RkSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRkSearchBarElementEventMap>(type: K, listener: (this: HTMLRkSearchBarElement, ev: RkSearchBarCustomEvent<HTMLRkSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRkSearchBarElementEventMap>(type: K, listener: (this: HTMLRkSearchBarElement, ev: RkSearchBarCustomEvent<HTMLRkSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRkSearchBarElement: {
        prototype: HTMLRkSearchBarElement;
        new (): HTMLRkSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "rk-badge": HTMLRkBadgeElement;
        "rk-empty-state": HTMLRkEmptyStateElement;
        "rk-filter-select": HTMLRkFilterSelectElement;
        "rk-ingredient-list": HTMLRkIngredientListElement;
        "rk-meal-slot": HTMLRkMealSlotElement;
        "rk-modal": HTMLRkModalElement;
        "rk-recipe-card": HTMLRkRecipeCardElement;
        "rk-search-bar": HTMLRkSearchBarElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * Small pill used for recipe categories, cuisines and tags.
     */
    interface RkBadge {
        /**
          * Text to render when no slotted content is provided.
          * @default ''
         */
        "label"?: string;
        /**
          * Visual treatment of the pill.
          * @default 'neutral'
         */
        "variant"?: 'neutral' | 'primary' | 'danger';
    }
    /**
     * Placeholder shown when a list has nothing to display.
     */
    interface RkEmptyState {
        /**
          * Bold headline, e.g. `"No recipes found"`.
          * @default 'Nothing here yet'
         */
        "heading"?: string;
        /**
          * Emoji or short glyph shown above the heading.
          * @default '🍳'
         */
        "icon"?: string;
        /**
          * Supporting sentence explaining what to do next.
          * @default ''
         */
        "message"?: string;
    }
    /**
     * Labelled dropdown used to narrow a recipe list.
     * `options` is an object array, so hosts must set it as a **property** rather
     * than an attribute. A JSON string is also accepted as a convenience for
     * server-rendered markup.
     */
    interface RkFilterSelect {
        /**
          * Disables the control, e.g. while its choices are still loading.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Visible label above the control.
          * @default ''
         */
        "label"?: string;
        /**
          * Echoed back in `rkFilterChange` so one handler can serve several filters.
         */
        "name": string;
        /**
          * Fired whenever the user picks a different option.
         */
        "onRkFilterChange"?: (event: RkFilterSelectCustomEvent<RkFilterChangeDetail>) => void;
        /**
          * Choices to render. Accepts an array or a JSON-encoded array.
          * @default []
         */
        "options"?: RkFilterOption[] | string;
        /**
          * Label for the "no filter" entry.
          * @default 'All'
         */
        "placeholder"?: string;
        /**
          * Currently selected option value. Empty string selects the reset entry.
          * @default ''
         */
        "value"?: string;
    }
    /**
     * Checklist of ingredients for the recipe details page.
     * `items` is an object array, so hosts set it as a **property**. A JSON string
     * is accepted as well. Ticking a row is local UI state - a shopping aid - so it
     * deliberately emits nothing.
     */
    interface RkIngredientList {
        /**
          * Renders checkboxes so the list doubles as a shopping list.
          * @default true
         */
        "checkable"?: boolean;
        /**
          * Section heading.
          * @default 'Ingredients'
         */
        "heading"?: string;
        /**
          * Ingredients to render. Accepts an array or a JSON-encoded array.
          * @default []
         */
        "items"?: RkIngredient[] | string;
    }
    /**
     * One cell of the weekly planner grid: either an assigned recipe or an empty
     * "add" target.
     */
    interface RkMealSlot {
        /**
          * Day key echoed back in every event, e.g. `"monday"`.
         */
        "day": string;
        /**
          * Meal key echoed back in every event, e.g. `"dinner"`.
         */
        "meal": string;
        /**
          * Label for the meal, defaults to a title-cased `meal`.
          * @default ''
         */
        "mealLabel"?: string;
        /**
          * Fired when an empty slot is activated - the host should open a picker.
         */
        "onRkAssign"?: (event: RkMealSlotCustomEvent<RkMealSlotDetail>) => void;
        /**
          * Fired when an assigned recipe is activated - the host should navigate.
         */
        "onRkOpen"?: (event: RkMealSlotCustomEvent<RkMealSlotDetail>) => void;
        /**
          * Fired when the remove button on a filled slot is pressed.
         */
        "onRkRemove"?: (event: RkMealSlotCustomEvent<RkMealSlotDetail>) => void;
        /**
          * Id of the assigned recipe. Empty renders the add-target state.
          * @default ''
         */
        "recipeId"?: string;
        /**
          * Title of the assigned recipe.
          * @default ''
         */
        "recipeName"?: string;
        /**
          * Thumbnail of the assigned recipe.
          * @default ''
         */
        "recipeThumbnail"?: string;
    }
    /**
     * Accessible dialog used for the "assign a recipe" and delete-confirmation flows.
     * Visibility is fully controlled by the host through `open`; the component only
     * asks to be closed by emitting `rkClose`.
     */
    interface RkModal {
        /**
          * Dialog heading, also used as its accessible name.
          * @default ''
         */
        "heading"?: string;
        /**
          * Hides the × button when the host wants to force a footer choice.
          * @default false
         */
        "hideCloseButton"?: boolean;
        /**
          * Fired on backdrop click, × press, or Escape.
         */
        "onRkClose"?: (event: RkModalCustomEvent<void>) => void;
        /**
          * Whether the dialog is visible.
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * Presentational card for a single recipe.
     * The card owns no state: the host decides whether it is favourited and reacts
     * to `rkFavoriteToggle` / `rkOpen`.
     */
    interface RkRecipeCard {
        /**
          * Text of the primary call-to-action.
          * @default 'View recipe'
         */
        "actionLabel"?: string;
        /**
          * Whether the recipe is currently favourited (drives the heart icon).
          * @default false
         */
        "favorite"?: boolean;
        /**
          * Hides the favourite button entirely, for read-only contexts.
          * @default false
         */
        "hideFavorite"?: boolean;
        /**
          * Recipe title shown as the card heading.
          * @default ''
         */
        "name"?: string;
        /**
          * Fired when the favourite button is pressed, with the desired next state.
         */
        "onRkFavoriteToggle"?: (event: RkRecipeCardCustomEvent<RkFavoriteToggleDetail>) => void;
        /**
          * Fired when the card or its primary action is activated.
         */
        "onRkOpen"?: (event: RkRecipeCardCustomEvent<string>) => void;
        /**
          * Identifier passed back in every emitted event.
         */
        "recipeId": string;
        /**
          * Thumbnail URL. A placeholder is drawn when omitted.
          * @default ''
         */
        "thumbnail"?: string;
    }
    /**
     * A debounced search input.
     * Emits `rkSearch` while the user types (debounced) and `rkSearchSubmit` when
     * they press Enter or the search button, so hosts can choose between
     * search-as-you-type and explicit submission.
     */
    interface RkSearchBar {
        /**
          * Milliseconds to wait after the last keystroke before emitting `rkSearch`.
          * @default 350
         */
        "debounce"?: number;
        /**
          * Accessible label for the input.
          * @default 'Search recipes'
         */
        "label"?: string;
        /**
          * Renders a spinner in place of the search icon.
          * @default false
         */
        "loading"?: boolean;
        /**
          * Fired after the debounce window with the current query.
         */
        "onRkSearch"?: (event: RkSearchBarCustomEvent<string>) => void;
        /**
          * Fired immediately on Enter or search-button press.
         */
        "onRkSearchSubmit"?: (event: RkSearchBarCustomEvent<string>) => void;
        /**
          * Placeholder text for the input.
          * @default 'Search recipes…'
         */
        "placeholder"?: string;
        /**
          * Current query. Kept in sync when the host changes it (e.g. clearing a search).
          * @default ''
         */
        "value"?: string;
    }

    interface RkBadgeAttributes {
        "label": string;
        "variant": 'neutral' | 'primary' | 'danger';
    }
    interface RkEmptyStateAttributes {
        "icon": string;
        "heading": string;
        "message": string;
    }
    interface RkFilterSelectAttributes {
        "name": string;
        "label": string;
        "value": string;
        "placeholder": string;
        "options": RkFilterOption[] | string;
        "disabled": boolean;
    }
    interface RkIngredientListAttributes {
        "heading": string;
        "items": RkIngredient[] | string;
        "checkable": boolean;
    }
    interface RkMealSlotAttributes {
        "day": string;
        "meal": string;
        "mealLabel": string;
        "recipeId": string;
        "recipeName": string;
        "recipeThumbnail": string;
    }
    interface RkModalAttributes {
        "open": boolean;
        "heading": string;
        "hideCloseButton": boolean;
    }
    interface RkRecipeCardAttributes {
        "recipeId": string;
        "name": string;
        "thumbnail": string;
        "favorite": boolean;
        "hideFavorite": boolean;
        "actionLabel": string;
    }
    interface RkSearchBarAttributes {
        "value": string;
        "placeholder": string;
        "debounce": number;
        "label": string;
        "loading": boolean;
    }

    interface IntrinsicElements {
        "rk-badge": Omit<RkBadge, keyof RkBadgeAttributes> & { [K in keyof RkBadge & keyof RkBadgeAttributes]?: RkBadge[K] } & { [K in keyof RkBadge & keyof RkBadgeAttributes as `attr:${K}`]?: RkBadgeAttributes[K] } & { [K in keyof RkBadge & keyof RkBadgeAttributes as `prop:${K}`]?: RkBadge[K] };
        "rk-empty-state": Omit<RkEmptyState, keyof RkEmptyStateAttributes> & { [K in keyof RkEmptyState & keyof RkEmptyStateAttributes]?: RkEmptyState[K] } & { [K in keyof RkEmptyState & keyof RkEmptyStateAttributes as `attr:${K}`]?: RkEmptyStateAttributes[K] } & { [K in keyof RkEmptyState & keyof RkEmptyStateAttributes as `prop:${K}`]?: RkEmptyState[K] };
        "rk-filter-select": Omit<RkFilterSelect, keyof RkFilterSelectAttributes> & { [K in keyof RkFilterSelect & keyof RkFilterSelectAttributes]?: RkFilterSelect[K] } & { [K in keyof RkFilterSelect & keyof RkFilterSelectAttributes as `attr:${K}`]?: RkFilterSelectAttributes[K] } & { [K in keyof RkFilterSelect & keyof RkFilterSelectAttributes as `prop:${K}`]?: RkFilterSelect[K] } & OneOf<"name", RkFilterSelect["name"], RkFilterSelectAttributes["name"]>;
        "rk-ingredient-list": Omit<RkIngredientList, keyof RkIngredientListAttributes> & { [K in keyof RkIngredientList & keyof RkIngredientListAttributes]?: RkIngredientList[K] } & { [K in keyof RkIngredientList & keyof RkIngredientListAttributes as `attr:${K}`]?: RkIngredientListAttributes[K] } & { [K in keyof RkIngredientList & keyof RkIngredientListAttributes as `prop:${K}`]?: RkIngredientList[K] };
        "rk-meal-slot": Omit<RkMealSlot, keyof RkMealSlotAttributes> & { [K in keyof RkMealSlot & keyof RkMealSlotAttributes]?: RkMealSlot[K] } & { [K in keyof RkMealSlot & keyof RkMealSlotAttributes as `attr:${K}`]?: RkMealSlotAttributes[K] } & { [K in keyof RkMealSlot & keyof RkMealSlotAttributes as `prop:${K}`]?: RkMealSlot[K] } & OneOf<"day", RkMealSlot["day"], RkMealSlotAttributes["day"]> & OneOf<"meal", RkMealSlot["meal"], RkMealSlotAttributes["meal"]>;
        "rk-modal": Omit<RkModal, keyof RkModalAttributes> & { [K in keyof RkModal & keyof RkModalAttributes]?: RkModal[K] } & { [K in keyof RkModal & keyof RkModalAttributes as `attr:${K}`]?: RkModalAttributes[K] } & { [K in keyof RkModal & keyof RkModalAttributes as `prop:${K}`]?: RkModal[K] };
        "rk-recipe-card": Omit<RkRecipeCard, keyof RkRecipeCardAttributes> & { [K in keyof RkRecipeCard & keyof RkRecipeCardAttributes]?: RkRecipeCard[K] } & { [K in keyof RkRecipeCard & keyof RkRecipeCardAttributes as `attr:${K}`]?: RkRecipeCardAttributes[K] } & { [K in keyof RkRecipeCard & keyof RkRecipeCardAttributes as `prop:${K}`]?: RkRecipeCard[K] } & OneOf<"recipeId", RkRecipeCard["recipeId"], RkRecipeCardAttributes["recipeId"]>;
        "rk-search-bar": Omit<RkSearchBar, keyof RkSearchBarAttributes> & { [K in keyof RkSearchBar & keyof RkSearchBarAttributes]?: RkSearchBar[K] } & { [K in keyof RkSearchBar & keyof RkSearchBarAttributes as `attr:${K}`]?: RkSearchBarAttributes[K] } & { [K in keyof RkSearchBar & keyof RkSearchBarAttributes as `prop:${K}`]?: RkSearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Small pill used for recipe categories, cuisines and tags.
             */
            "rk-badge": LocalJSX.IntrinsicElements["rk-badge"] & JSXBase.HTMLAttributes<HTMLRkBadgeElement>;
            /**
             * Placeholder shown when a list has nothing to display.
             */
            "rk-empty-state": LocalJSX.IntrinsicElements["rk-empty-state"] & JSXBase.HTMLAttributes<HTMLRkEmptyStateElement>;
            /**
             * Labelled dropdown used to narrow a recipe list.
             * `options` is an object array, so hosts must set it as a **property** rather
             * than an attribute. A JSON string is also accepted as a convenience for
             * server-rendered markup.
             */
            "rk-filter-select": LocalJSX.IntrinsicElements["rk-filter-select"] & JSXBase.HTMLAttributes<HTMLRkFilterSelectElement>;
            /**
             * Checklist of ingredients for the recipe details page.
             * `items` is an object array, so hosts set it as a **property**. A JSON string
             * is accepted as well. Ticking a row is local UI state - a shopping aid - so it
             * deliberately emits nothing.
             */
            "rk-ingredient-list": LocalJSX.IntrinsicElements["rk-ingredient-list"] & JSXBase.HTMLAttributes<HTMLRkIngredientListElement>;
            /**
             * One cell of the weekly planner grid: either an assigned recipe or an empty
             * "add" target.
             */
            "rk-meal-slot": LocalJSX.IntrinsicElements["rk-meal-slot"] & JSXBase.HTMLAttributes<HTMLRkMealSlotElement>;
            /**
             * Accessible dialog used for the "assign a recipe" and delete-confirmation flows.
             * Visibility is fully controlled by the host through `open`; the component only
             * asks to be closed by emitting `rkClose`.
             */
            "rk-modal": LocalJSX.IntrinsicElements["rk-modal"] & JSXBase.HTMLAttributes<HTMLRkModalElement>;
            /**
             * Presentational card for a single recipe.
             * The card owns no state: the host decides whether it is favourited and reacts
             * to `rkFavoriteToggle` / `rkOpen`.
             */
            "rk-recipe-card": LocalJSX.IntrinsicElements["rk-recipe-card"] & JSXBase.HTMLAttributes<HTMLRkRecipeCardElement>;
            /**
             * A debounced search input.
             * Emits `rkSearch` while the user types (debounced) and `rkSearchSubmit` when
             * they press Enter or the search button, so hosts can choose between
             * search-as-you-type and explicit submission.
             */
            "rk-search-bar": LocalJSX.IntrinsicElements["rk-search-bar"] & JSXBase.HTMLAttributes<HTMLRkSearchBarElement>;
        }
    }
}
